### ISSUE TITLE
macOS无法打开app

### ISSUE THREAD

**Issue by DelmarHuang** [sethyuan/orca-note#1]
macOS：13.2.1 (22D68)
Mac：MBP2017

安装的最近的三个版本均报错如下：

<img width="503" alt="image" src="https://github.com/user-attachments/assets/f3a2aa72-34d7-4039-88a9-8949e2840347">

感觉app大小也不对。不过就算之前有一次显示340MB也同样报错。尝试ChatGPT教我的几种方法，都失败了。麻烦有空的时候帮忙看下，谢谢

<img width="531" alt="image" src="https://github.com/user-attachments/assets/b0a6f078-8040-4630-a437-6c1751612ca5">

**Comment by sethyuan** [comment]
大小确实不对，我看了下我这边，App有347MB左右，dmg应该有130MB左右，可以看看是不是网络问题。另外记得下载适合你处理器的版本，M芯片的下载arm64那个，Intel芯片的下载x64那个。

还有macOS M芯片下首次运行暂时需要先执行下以下命令，绕过苹果的签名检查，因为目前App还处于内测，没有做签名：

```
xattr -r -d com.apple.quarantine /Applications/Orca\ Note.app
```

**Comment by sethyuan** [comment]
大小不一样是正常的，我说的大小是arm64的。你运行过上面提到的排除检查签名的命令没？没有的话需要运行一下。我刚下了x64的版本在我的M芯片的Mac上也是可以运行的（通过Rosetta）。

**Comment by DelmarHuang** [comment]
@sethyuan 用了也不行，sudo xattr -rd com.apple.quarantine 用了这条命令也不行。在试之前，已经卸载、重启、重装0.11版本的，还是报一样的错 
<img width="531" alt="image" src="https://github.com/user-attachments/assets/da24f6d9-9bfd-4471-84d9-054ad5d9bf81">
<img width="511" alt="image" src="https://github.com/user-attachments/assets/a914daff-f70d-4421-ac84-e48068285745">

**Comment by sethyuan** [comment]
@DelmarHuang 我感觉你是不是之前没给应用访问Documents的权限？取决于系统版本，但第一次运行时系统会提示要不要给访问权限，如果你选否的话应用就会因为没有权限而被限制。

**Comment by sethyuan** [comment]
确认是没给文件权限问题。

**Comment by DelmarHuang** [comment]
> 确认是没给文件权限问题。

@sethyuan 我安装了0.20.1，还是不行，也没有任何提示让我给权限，我自己也手动添加不了

**Comment by sethyuan** [comment]
@DelmarHuang 

看看这里的设置对不对，不对改一下：

![image](https://github.com/user-attachments/assets/e8cec7e7-5fbe-4aca-b1fe-bfa33f6dc9ca)

**Comment by sethyuan** [comment]
这就有点摸不着头脑了，会不会你的系统中被做了什么限制？按说默认不会给全部磁盘权限，也不可能没法修改。
