### ISSUE TITLE
Task 作为标签，打开的时候没有“表格”选项

### ISSUE THREAD

**Issue by kathleensun** [sethyuan/orca-note#10]
Task 作为标签，打开的时候没有“表格”选项

<img width="1094" alt="image" src="https://github.com/user-attachments/assets/0d1e7ae8-d96e-4504-8961-558a5a0906d8" />

**Comment by sethyuan** [comment]
是最新的版本吗？看起来不像。

**Comment by kathleensun** [comment]
已经更新到 0.21.0，还是一样的。

**Comment by sethyuan** [comment]
那你的Task应该不是标签，你看看它有没有别名，标签是有别名的。

**Comment by kathleensun** [comment]
可是 Task 是插件，不是我设置的标签，（是不是更新版本之后，需要重新安装插件？）

**Comment by sethyuan** [comment]
@kathleensun 嗯，最新版需要把插件也更新到最新。另外你可以检查下你的插件设置，下面是我的设置：

![image](https://github.com/user-attachments/assets/8172fba6-0a19-4560-af42-1dd1c963752e)

你应该能在标签列表里看到配置的标签：

![image](https://github.com/user-attachments/assets/7c868ddd-87ca-4262-9fd2-0765b610b489)

**Comment by kathleensun** [comment]
我更新到了新版本，0.22，重新安装了插件，问题解决
