### ISSUE TITLE
无需列表状态的文本，只能在文末回车，无法在中间段落点回车

### ISSUE THREAD

**Issue by zhonghaojay** [sethyuan/orca-note#2]
有序列表没有这个问题

**Comment by mzwlevi** [comment]
我下了最新版本，看样子是修复了，你可以试下
![CleanShot 2024-11-27 at 20 05 30@2x](https://github.com/user-attachments/assets/bf9df344-8e84-456e-88a2-69e314449660)

**Comment by sethyuan** [comment]
@zhonghaojay 我也在最新版里试了一下，已经修好了。 😂
