### ISSUE TITLE
win端删除表格会报错

### ISSUE THREAD

**Issue by 3217333857** [sethyuan/orca-note#3]

**Comment by sethyuan** [comment]
能否提供一下能重现的示例？什么样的情况下删除会报错？

**Comment by 3217333857** [comment]
![image](https://github.com/user-attachments/assets/afcc9e03-0aa6-478d-97e7-bd009721a91b)
![image](https://github.com/user-attachments/assets/3c745164-7aa6-43bc-b0c5-55c1587ac6dc)
![image](https://github.com/user-attachments/assets/91ac2c61-5413-4183-9f6b-69cc3a964787)

**Comment by 3217333857** [comment]
如图二所示，选中那些文本删除便会报错

**Comment by sethyuan** [comment]
好的，我跟一下。

**Comment by sethyuan** [comment]
@3217333857 FYI，这个已经修复了。
