### ISSUE TITLE
请教为什么没有 TODO 选项

### ISSUE THREAD

**Issue by kathleensun** [sethyuan/orca-note#9]
我的理解，都会默认 /选项中会有 TASK 选项。

发现目前没有，不知道是不是设计就是这样的。

**Comment by sethyuan** [comment]
虎鲸笔记默认不包含task功能，但是我开发了一个插件利用虎鲸笔记的标签提供了task的功能，具体可看下[simple-task](https://github.com/sethyuan/orca-simple-task)。

**Comment by kathleensun** [comment]
解决了，设计的很精巧，图标有好几个选项来显示 Task 的进展，很棒！
